t = linspace(0, 1, 1000); 
clean_signal = sin(2 * pi * 5 * t); 
SNR = 10;
noisy_signal = awgn(clean_signal, SNR, 'measured');
order = 10; 
wiener_filter = fir1(order, 0.5); 
estimated_clean_signal = filter(wiener_filter, 1, noisy_signal);
figure;
subplot(3, 1, 1);
plot(t, clean_signal);
title('Original (Clean) Signal');
xlabel('Time');
ylabel('Amplitude');
subplot(3, 1, 2);
plot(t, noisy_signal);
title('Noisy Signal');
xlabel('Time');
ylabel('Amplitude');
subplot(3, 1, 3);
plot(t, estimated_clean_signal);
title('Estimated Clean Signal (Wiener Filter Output)');
xlabel('Time');
ylabel('Amplitude');